const BASE_URL = "http://localhost:8080"
export const IMAGES_URL = BASE_URL + "/construction-images/"
export const GET_CONSTRUCTION_IMAGES_BY_ARCHITECTURAL_STYLE_URL = BASE_URL + "/construction-images/architectural-styles/"
export const ARCHITECTURAL_STYLES_URL = BASE_URL + "/architectural-styles/"
export const ARCHITECTS_URL = BASE_URL + "/architects/"
